[package]
name = "cntk"
description = "Wrapper around Microsoft CNTK library"
license = "MIT license"
version = "0.0.1"
authors = ["Vlado Boza <vlado@raptorintelligence.com>"]

build = "build.rs"

[dependencies]
cpp = "0.3.2"

[build-dependencies]
cpp_build = "0.3.2"
